In [1]:
# import numpy
import numpy as np

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# create a numpy array np.arrar(anylist/any data/any list/any tuple/any dicti)
# create an simple list
arr = np.array([1,4,6,7,8])
arr

array([1, 4, 6, 7, 8])

In [3]:
# check data type . dtype(arrayname)
type(arr)

numpy.ndarray

### 1) Converting Python sequences to NumPy Arrays

In [4]:
# 1D array as like list
# 2D array , 2 rows
# 3D array , 3 rows

# create 1 D array
a1 = np.array([8,6,7,25,89,13])
a1

array([ 8,  6,  7, 25, 89, 13])

In [5]:
# Create 2D array
a2 = np.array([[4,6,8,10],[3,5,7,9]])
a2

array([[ 4,  6,  8, 10],
       [ 3,  5,  7,  9]])

In [6]:
# Create 3D array 2*3 , 2 row 3 col
a3 = np.array([[[12,13,14],[34,45,46]],[[45,56,7],[45,6,8]]])
a3

array([[[12, 13, 14],
        [34, 45, 46]],

       [[45, 56,  7],
        [45,  6,  8]]])

#### Numpy array default dtype int64. if i want to change it into int32 or float then must be idetify it.

In [7]:
a4 = np.array([4,6,7,3.6,4.90], dtype= np.int8)
a4

array([4, 6, 7, 3, 4], dtype=int8)

In [8]:
a5 = np.array([3,5,6,7,8], dtype=float)
a5

array([3., 5., 6., 7., 8.])

### 2) Intrinsic NumPy array creation functions

NumPy has over 40 built-in functions for creating arrays as laid out in the Array creation routines. These functions can be split into roughly three categories, based on the dimension of the array they create:

1D arrays

2D arrays

ndarrays

### 1 - 1D array creation functions
The 1D array creation functions e.g. numpy.linspace and numpy.arange generally need at least two inputs, start and stop.

In [9]:
# arrange(start,end,step,dtype=np.any)
# create a 1D array usings arange()
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# create a 1D array which start form 2 and end 11 and step will be 2
a1 = np.arange(2,11,2,dtype=np.float32)
a1

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)

In [11]:
# reshape--- can convert array different rows and columns shape
# if i want 3 rows and 2 cols then

a2 = np.arange(9).reshape((3,3))
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####  numpy.linspace
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [12]:
#  np.linespace
# create an array start from 2 and end 10 , step 3
a3 = np.linspace(2, 10, num=14, endpoint=True)
a3

array([ 2.        ,  2.61538462,  3.23076923,  3.84615385,  4.46153846,
        5.07692308,  5.69230769,  6.30769231,  6.92307692,  7.53846154,
        8.15384615,  8.76923077,  9.38461538, 10.        ])

In [13]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [14]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [15]:
# empty([]) with shape. 3 rows 4 cols
np.empty([3,4])

array([[7.16866224e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 6.82116729e-043, 5.25254645e-090,
        3.37796300e-057],
       [5.41991786e-067, 1.82878453e+184, 3.99910963e+252,
        4.27632321e-033]])

###  eye
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None) <br>
Return a 2-D array with ones on the diagonal and zeros elsewhere

In [16]:
# n -- number of rows, M-- number of cols
# diagonal matrics
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.identity
numpy.identity(n, dtype=None, *, like=None) <br>

The identity array is a square array with ones on the main diagonal.

In [17]:
# same as eye just different no need to specify rows and cols
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.ones
numpy.ones(shape, dtype=None, order='C', *, like=None)<br>
Return a new array of given shape and type, filled with ones.

In [18]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [22]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# convert any array into ones array using ones_like()
x = np.arange(6).reshape(2,3)
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
y = np.arange(10)
np.ones_like(y)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
z = np.arange(9).reshape((3,3))
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.ones_like(z)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### numpy.zeros
numpy.zeros(shape, dtype=float, order='C', *, like=None) <br>
Return a new array of given shape and type, filled with zeros.

In [24]:
np.zeros_like(z)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
# create a zero matrics
# 4 rows and 6 cols
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### numpy.full
numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)<br>
Return a new array of given shape and type, filled with fill_value.

In [26]:
# Create an 1d array with fill value
np.full(3,2)

array([2, 2, 2])

## numpy.full_like
numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None) <br>
Return a full array with the same shape and type as a given array.

In [27]:
np.full_like(z,3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [28]:
# create 3 array
# 1D
x = np.arange(9)
# 2D
y = np.arange(12).reshape(3,4)
# 2 rows , 3 rows, 2 cols. 3D
z = np.arange(12).reshape(2,3,2)
x,y,z

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]))

In [29]:
# ndarray.shape -- show how mane rows and cols are there
# Tuple of array dimensions.
x.shape
y.shape
z.shape

(2, 3, 2)

In [30]:
#numpy.ndarray.ndim check Number of array dimensions.
x.ndim

1

In [31]:
y.ndim

2

In [32]:
z.ndim

3

In [33]:
## ndarray.size
## Number of elements in the array.
z.size

12

In [34]:
# ndarray.itemsize . Length of one array element in bytes.
x.itemsize

4

In [35]:
# dtype--- checking which data dtype
x.dtype

dtype('int32')

In [36]:
y.dtype

dtype('int32')

### Changing Datatype

In [37]:
k = x.astype(np.int32)

In [38]:
k.dtype

dtype('int32')

### Array Operations

In [39]:
# if number of rows and number of sols are equal then can do operatrons
x+y

ValueError: operands could not be broadcast together with shapes (9,) (3,4) 

In [40]:
p = np.arange(9).reshape(3,3)
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
q = np.arange(9).reshape(3,3)
np.full_like(q,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [42]:
p + q

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [43]:
p-q

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
p*q

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [45]:
p*5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [46]:
p**3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

### Array Functions

In [47]:
import numpy as np

In [48]:
# create an array with random value
a1 = np.random.random((4,5))
a1

array([[0.21904116, 0.14416275, 0.56246175, 0.37704744, 0.46892213],
       [0.17279351, 0.5693337 , 0.94127018, 0.76190119, 0.53786093],
       [0.88342383, 0.78711516, 0.38965889, 0.75598575, 0.51738346],
       [0.89905657, 0.84633578, 0.17829383, 0.92557439, 0.31515395]])

In [49]:
 # round
 a = np.round(a1*100)
 a

array([[22., 14., 56., 38., 47.],
       [17., 57., 94., 76., 54.],
       [88., 79., 39., 76., 52.],
       [90., 85., 18., 93., 32.]])

### numpy.max(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>) <br>
Return the maximum of an array or maximum along an axis

In [50]:
# axis 1 means all row
# axis=0 means all cols
a.max(axis=1)

array([56., 94., 88., 93.])

In [51]:
a.max(axis=0)

array([90., 85., 94., 93., 54.])

In [52]:
a.min(axis=1)

array([14., 17., 39., 18.])

In [53]:
np.exp(a)

array([[3.58491285e+09, 1.20260428e+06, 2.09165950e+24, 3.18559318e+16,
        2.58131289e+20],
       [2.41549528e+07, 5.68572000e+24, 6.66317622e+40, 1.01480039e+33,
        2.83075330e+23],
       [1.65163625e+38, 2.03828107e+34, 8.65934004e+16, 1.01480039e+33,
        3.83100800e+22],
       [1.22040329e+39, 8.22301271e+36, 6.56599691e+07, 2.45124554e+40,
        7.89629602e+13]])

### Indexing and Slicing

In [54]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   # create 3 array
# 1D
x = np.arange(9)
# 2D
y = np.arange(12).reshape(3,4)
# 2 rows , 3 rows, 2 cols. 3D
z = np.arange(12).reshape(2,3,2)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
z

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [58]:
# calculation start from 0
# 0,0 = row 0, col 0,  5,3 = row 5 col 3 value
# show array value 4 from 2d array
y[1,0]

4

In [59]:
# show 11 values from 3D array - [3d row, 2D row, col no]
z[1,2,1]

11

In [60]:
# show 5 value from 3d array
z[0,2,1]

5

### Slicing

In [61]:
#[start:end:step] 1D array
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
# show 4,5,6 no value from 1D array
x[4:6]

array([4, 5])

In [63]:
# show 4 to 8 values only even no
x[4:8:3]

array([4, 7])

In [64]:
#  from start to 4
x[:4]

array([0, 1, 2, 3])

In [65]:
x[::4]

array([0, 4, 8])

In [66]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [67]:
# 2D array slicing
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
# whant to show 3
y[2:4]

array([[ 8,  9, 10, 11]])

In [69]:
#[rows:cols,cols:cols]
y[0:2, 1:2]

array([[1],
       [5]])

In [70]:
y[2::,2::]

array([[10, 11]])

In [71]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
# show 5 6 9 10
y[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [73]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
w = np.arange(16).reshape((4,4))
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
# show 5 6, 9 10, 13 14
#[rows:rows,cols:cols]
w[1:2, 1:2]

array([[5]])

In [76]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
# show 10 row, cols
w[2,2]

10

In [78]:
# 10 11 , 14,15
w[2::, 2::]

array([[10, 11],
       [14, 15]])

In [79]:
# 5 6, 9, 10
w[1:3, 1::]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [80]:
k = np.arange(20).reshape(4,5)
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
#[rows:rows, cols:cols]
#select rows in index positions 1 through 3
k[1:3, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
#select columns in index positions 1 through 3
k[:, 1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [83]:
#select rows in 2:4 and columns in 1:3
k[2:4, 1:3]

array([[11, 12],
       [16, 17]])

In [84]:
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
# 7 8 , 12 13
k[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

### 3D array slicing

In [86]:
t = np.arange(36).reshape(4,3,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [87]:
# 1st and 3rd row, 1st and 2nd row 1st and 2nd column value
t[::2, 1::, 1::]

array([[[ 4,  5],
        [ 7,  8]],

       [[22, 23],
        [25, 26]]])

In [88]:
t

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [89]:
t[0,1::, 1::]

array([[4, 5],
       [7, 8]])

### Iterating

In [90]:
# 1D array value show
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
for i in x:
  print(i)

0
1
2
3
4
5
6
7
8


In [92]:
for i in np.nditer(y):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [93]:
# Transpose: row col abd col row
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
y.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
# ravel convert 1D array
np.ravel(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])