### np.sort

Return a sorted copy of an array.
apply it 1D array and 2D array also

In [9]:
# 1D array
import numpy as np
a = np.random.randint(1,100,20)
a

array([34, 66, 67, 56, 70, 46, 31, 55, 53, 51, 85, 32, 13, 58, 19, 37, 72,
       10, 65, 18])

In [10]:
# 2D array
b = np.random.randint(5,100,24).reshape(6,4)
b

array([[28, 41, 72, 28],
       [41, 22, 10, 54],
       [34, 94, 92, 82],
       [10, 38, 82, 73],
       [45, 69, 42, 68],
       [45, 77, 85, 53]])

In [11]:
# sorting 1D array
np.sort(a)

array([10, 13, 18, 19, 31, 32, 34, 37, 46, 51, 53, 55, 56, 58, 65, 66, 67,
       70, 72, 85])

In [12]:
# sorting 2D array
# note, axis = 0 means cols and axis = 1 means rows
np.sort(b,axis=1)

array([[28, 28, 41, 72],
       [10, 22, 41, 54],
       [34, 82, 92, 94],
       [10, 38, 73, 82],
       [42, 45, 68, 69],
       [45, 53, 77, 85]])

In [13]:
# sort cols
np.sort(b,axis=0)

array([[10, 22, 10, 28],
       [28, 38, 42, 53],
       [34, 41, 72, 54],
       [41, 69, 82, 68],
       [45, 77, 85, 73],
       [45, 94, 92, 82]])

In [14]:
# sort last to first
# last to first indexing ::-1
np.sort(a)[::-1]

array([85, 72, 70, 67, 66, 65, 58, 56, 55, 53, 51, 46, 37, 34, 32, 31, 19,
       18, 13, 10])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array.
not sum just add any values 1D array. 
add 1 rows or 1 cols values an exiting array.<br>
structure: numpy.append(arr, values, axis=None)

In [15]:
# want to add 100 , 200 in 1D array
np.append(a,[100,200])

array([ 34,  66,  67,  56,  70,  46,  31,  55,  53,  51,  85,  32,  13,
        58,  19,  37,  72,  10,  65,  18, 100, 200])

In [16]:
# want to add 5 values in 2D array 
np.append(b,[20,40,55,65,23,63], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [17]:
# want to add 4 values in 2D array 
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[2.80000000e+01, 4.10000000e+01, 7.20000000e+01, 2.80000000e+01,
        3.59246017e-02],
       [4.10000000e+01, 2.20000000e+01, 1.00000000e+01, 5.40000000e+01,
        5.65008718e-01],
       [3.40000000e+01, 9.40000000e+01, 9.20000000e+01, 8.20000000e+01,
        4.50836337e-01],
       [1.00000000e+01, 3.80000000e+01, 8.20000000e+01, 7.30000000e+01,
        7.94021837e-01],
       [4.50000000e+01, 6.90000000e+01, 4.20000000e+01, 6.80000000e+01,
        2.61697407e-01],
       [4.50000000e+01, 7.70000000e+01, 8.50000000e+01, 5.30000000e+01,
        6.20120735e-01]])

In [18]:
np.random.random((b.shape[0],1))

array([[0.87948186],
       [0.06157138],
       [0.7875532 ],
       [0.27243748],
       [0.2420559 ],
       [0.19276476]])

### np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.<br>
struture: numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind"

In [19]:
# shape must be same
c = np.arange(6).reshape(2,3)
d = np.arange(4,10).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
d

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
# default cols
np.concatenate((c,d))

array([[0, 1, 2],
       [3, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# add rows way rows + rows
np.concatenate((c,d), axis=1)

array([[0, 1, 2, 4, 5, 6],
       [3, 4, 5, 7, 8, 9]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.<br>
Structure: numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)

In [23]:
# show is there any unique values an array if its have which position
np.unique(c)

array([0, 1, 2, 3, 4, 5])

In [24]:
e = np.array([1,1,1,1,1,1,3,4,5,6,7,8,9,9,9,11,11,12,14,15,16,17,14,15])
np.unique(e)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 11, 12, 14, 15, 16, 17])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array. <br>
structure: numpy.expand_dims(a, axis)

In [25]:
f = np.array([10,20,30,40])
np.shape(f)

(4,)

In [26]:
# convert it into 2D array
g = np.expand_dims(f,axis=1)
np.shape(g)

(4, 1)

In [27]:
np.expand_dims(f,axis=0)

array([[10, 20, 30, 40]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied. <br>
structure: numpy.where(condition, [x, y, ]/) <br>
numpy.where(condition, tru, false) <br>
When only condition is provided, this function is a shorthand for np.asarray(condition).nonzero(). Using nonzero directly should be preferred, as it behaves correctly for subclasses. The rest of this documentation covers only the case where all three arguments are provided


In [28]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  3,  4,  7,  8,  9, 10, 13, 16, 18], dtype=int64),)

In [29]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([34,  0,  0,  0,  0, 46, 31,  0,  0,  0,  0, 32, 13,  0, 19, 37,  0,
       10,  0, 18])

In [30]:
# replce all valeus a%2==0 with 0 otherwise a
np.where(a%2==0, 0,a)

array([ 0,  0, 67,  0,  0,  0, 31, 55, 53, 51, 85,  0, 13,  0, 19, 37,  0,
        0, 65,  0])

### np.argmax
### np.argmin as like np.argmax. just retrun it minimum values index
The numpy.argmax() function returns indices of the max element of the array in a particular axis.<br>
structure: numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>) <br>

In [31]:
# find where is the maximum values located. or find maximum values index
a

array([34, 66, 67, 56, 70, 46, 31, 55, 53, 51, 85, 32, 13, 58, 19, 37, 72,
       10, 65, 18])

In [32]:
# from 1d array
np.argmax(a)

10

In [33]:
# from 2D array
b

array([[28, 41, 72, 28],
       [41, 22, 10, 54],
       [34, 94, 92, 82],
       [10, 38, 82, 73],
       [45, 69, 42, 68],
       [45, 77, 85, 53]])

In [34]:
np.argmax(a,axis=0)

10

In [35]:
np.argmax(b, axis=1)

array([2, 3, 1, 2, 1, 2], dtype=int64)

In [36]:
np.argmin(b)

6

In [37]:
np.argmin(b,axis=1)

array([0, 2, 0, 0, 2, 0], dtype=int64)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis. <br>
Structure: numpy.cumsum(a, axis=None, dtype=None, out=None)


In [38]:
np.cumsum(a)

array([ 34, 100, 167, 223, 293, 339, 370, 425, 478, 529, 614, 646, 659,
       717, 736, 773, 845, 855, 920, 938])

In [39]:
print(np.cumprod(a))

[         34        2244      150348     8419488   589364160  1340947584
 -1380297856  1393029248   816106112 -1328261248 -1233056384  -803098624
 -1850347520    54026240  1026498560  -674258944 -1302003712  -135135232
  -193855488   805568512]


In [40]:
# rows comulative sum
np.cumsum(b,axis=1)

array([[ 28,  69, 141, 169],
       [ 41,  63,  73, 127],
       [ 34, 128, 220, 302],
       [ 10,  48, 130, 203],
       [ 45, 114, 156, 224],
       [ 45, 122, 207, 260]])

In [41]:
# cols cumulative sum
np.cumsum(b,axis=0)

array([[ 28,  41,  72,  28],
       [ 69,  63,  82,  82],
       [103, 157, 174, 164],
       [113, 195, 256, 237],
       [158, 264, 298, 305],
       [203, 341, 383, 358]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.  <br>
####  structure: numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None) <br>
### percentile defination:
In statistics, a percentile is a term that describes how a score compares to other scores from the same set. While there is no universal definition of percentile, it is commonly expressed as the percentage of values in a set of data scores that fall below a given value. 
#### Fromula:  P = n/N * 100% , N= number of population, n = number of sample

#### example: What is the 95% percentile?
What's the 95th percentile? In networking, the 95th percentile is the highest value remaining after the top 5% of a data set is removed. For example, if you have 100 data points, you begin by removing the five largest values. The highest value left represents the 95th percentile.



In [42]:
np.percentile(a,50)

52.0

In [43]:
np.percentile(c,d)

array([[0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45]])

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form. <br>
#### Structure: numpy.histogram(a, bins=10, range=None, density=None, weights=None)

In [44]:
np.histogram(a,bins=[0,50,100])

(array([ 9, 11], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.
#### Structure: numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
### The correlation coefficient is measured on a scale that varies from + 1 through 0 to – 1. Complete correlation between two variables is expressed by either + 1 or -1. When one variable increases as the other increases the correlation is positive; when one decreases as the other increases it is negative.

In [45]:
# shape will be same
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.<br>
#### Structure: numpy.isin(element, test_elements, assume_unique=False, invert=False, *, kind=None)
https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [46]:
np.isin(a,12)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [47]:
h = np.arange(24).reshape(4,6)
i = np.arange(36).reshape(6,6)

In [48]:
h[np.isin(h,i)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.<br>
#### numpy.flip(m, axis=None)

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [49]:
# same ag negative indexing and slicing
np.flip(a)

array([18, 65, 10, 72, 37, 19, 58, 13, 32, 85, 51, 53, 55, 31, 46, 70, 56,
       67, 66, 34])

In [50]:
a[::-1]

array([18, 65, 10, 72, 37, 19, 58, 13, 32, 85, 51, 53, 55, 31, 46, 70, 56,
       67, 66, 34])

In [51]:
# 2D 
b

array([[28, 41, 72, 28],
       [41, 22, 10, 54],
       [34, 94, 92, 82],
       [10, 38, 82, 73],
       [45, 69, 42, 68],
       [45, 77, 85, 53]])

In [52]:
np.flip(b,axis=1)

array([[28, 72, 41, 28],
       [54, 10, 22, 41],
       [82, 92, 94, 34],
       [73, 82, 38, 10],
       [68, 42, 69, 45],
       [53, 85, 77, 45]])

In [53]:
np.flip(b,axis=0)

array([[45, 77, 85, 53],
       [45, 69, 42, 68],
       [10, 38, 82, 73],
       [34, 94, 92, 82],
       [41, 22, 10, 54],
       [28, 41, 72, 28]])

In [54]:
np.sort(b,axis=1)

array([[28, 28, 41, 72],
       [10, 22, 41, 54],
       [34, 82, 92, 94],
       [10, 38, 73, 82],
       [42, 45, 68, 69],
       [45, 53, 77, 85]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html
#### Structure: numpy.put(a, ind, v, mode='raise')

In [55]:
a

array([34, 66, 67, 56, 70, 46, 31, 55, 53, 51, 85, 32, 13, 58, 19, 37, 72,
       10, 65, 18])

In [56]:
# what to replace 38 to 100
np.put(a,6,100)

In [57]:
a

array([ 34,  66,  67,  56,  70,  46, 100,  55,  53,  51,  85,  32,  13,
        58,  19,  37,  72,  10,  65,  18])

In [58]:
# multiple repacing
np.put(a,[0,1],[110,530])

In [59]:
a

array([110, 530,  67,  56,  70,  46, 100,  55,  53,  51,  85,  32,  13,
        58,  19,  37,  72,  10,  65,  18])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html
#### numpy.delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj]

In [60]:
np.delete(a,[0,2,4])

array([530,  56,  46, 100,  55,  53,  51,  85,  32,  13,  58,  19,  37,
        72,  10,  65,  18])

### Set functions: but output will be array . must be sape will be same

- np.union1d --- add 2 set
- np.intersect1d --- intersect 2 set
- np.setdiff1d -- 
- np.setxor1d
- np.in1d

#### numpy.union1d
##### numpy.union1d(ar1, ar2)
Find the union of two arrays.<br>
Return the unique, sorted array of values that are in either of the two input arrays.

In [61]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
# common and uncommon all values
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
# only common values
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
# Find the set difference of two arrays.
np.setdiff1d(m,n)

array([1, 2])

In [64]:
# Return the sorted, unique values that are in only one (not both) of the input arrays.
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [65]:
# Returns a boolean array the same length as ar1 that is True where an element of ar1 is in ar2 and False otherwise
np.in1d(m,n)

array([False, False,  True,  True,  True])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html
#### numpy.clip
numpy.clip(a, a_min, a_max, out=None, **kwargs)<br>
Clip (limit) the values in an array. <br>

Given an interval, values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, and values larger than 1 become 1.<br>

Equivalent to but faster than np.minimum(a_max, np.maximum(a, a_min)).

No check is performed to ensure a_min < a_max.

In [66]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 67, 56, 70, 46, 75, 55, 53, 51, 75, 32, 25, 58, 25, 37, 72,
       25, 65, 25])

### numpy.swapaxes
#### numpy.swapaxes(a, axis1, axis2)
Interchange two axes of an array

In [67]:
# 2D array
b

array([[28, 41, 72, 28],
       [41, 22, 10, 54],
       [34, 94, 92, 82],
       [10, 38, 82, 73],
       [45, 69, 42, 68],
       [45, 77, 85, 53]])

In [68]:
np.swapaxes(b,0,1)

array([[28, 41, 34, 10, 45, 45],
       [41, 22, 94, 38, 69, 77],
       [72, 10, 92, 82, 42, 85],
       [28, 54, 82, 73, 68, 53]])