In [1]:
# Creating Numpy array
import numpy as np
# 1D array
a1 = np.array([10,20,30,40,50,60,70,80,90])
a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [2]:
# 2D array
a2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [3]:
# 3D array
a3 = np.array([[[10,20,30],[40,50,60],[70,80,90]],
              [[100,110,120],[130,140,150],[160,170,180]],
              [[190,200,210],[220,230,240],[250,260,270]]
             ])
a3

array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 110, 120],
        [130, 140, 150],
        [160, 170, 180]],

       [[190, 200, 210],
        [220, 230, 240],
        [250, 260, 270]]])

In [4]:
# Data type
np.array([12,4,6,], dtype=float)

array([12.,  4.,  6.])

In [5]:
# arange - create 1D array unisng arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 2D array using using arange
np.arange(3,30,10) # 10 - step number , 3-> starting value , 30 - ending value

array([ 3, 13, 23])

In [7]:
# using reshape and arange can create ant dimnetional array
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11).reshape(5,2) # 5 rows 2 col - 2D

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
np.arange(1,9).reshape(2,2,2) # 3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
np.arange(1,28).reshape(3,3,3) # 3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
np.arange(1,19).reshape(3,3,2) # 3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [12]:
# np.ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros(18).reshape(6,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#np.random
np.random.random(10) # 1D

array([0.09033304, 0.31649676, 0.9488267 , 0.59306595, 0.54909135,
       0.42814857, 0.36457218, 0.23496822, 0.91225232, 0.98630508])

In [16]:
np.random.random((4,5)) # 2D

array([[0.33310459, 0.16851215, 0.12220099, 0.86208488, 0.80180939],
       [0.75605445, 0.77896433, 0.2717213 , 0.94116531, 0.55940977],
       [0.24896525, 0.09021769, 0.49203274, 0.58417652, 0.28064119],
       [0.13768945, 0.41335181, 0.39169054, 0.49594956, 0.25609451]])

In [17]:
np.random.random((4,5,3)) # 3D

array([[[0.3329813 , 0.7423481 , 0.67795785],
        [0.6868582 , 0.83651216, 0.81324043],
        [0.7678667 , 0.26088463, 0.67402795],
        [0.67924471, 0.9124274 , 0.22593839],
        [0.49301326, 0.56357537, 0.53918006]],

       [[0.15395414, 0.19435645, 0.85446829],
        [0.82006153, 0.27840092, 0.83300198],
        [0.583949  , 0.22666833, 0.70126707],
        [0.57149822, 0.6437242 , 0.74290693],
        [0.40934124, 0.63796555, 0.73793885]],

       [[0.39029969, 0.20217817, 0.0733674 ],
        [0.91809814, 0.46187092, 0.60068283],
        [0.96463103, 0.57448224, 0.33029957],
        [0.44264591, 0.74092214, 0.62113739],
        [0.7628631 , 0.56621274, 0.78887653]],

       [[0.72947456, 0.23771312, 0.66375976],
        [0.11555152, 0.94757389, 0.35456529],
        [0.87929839, 0.72004791, 0.16013798],
        [0.5798929 , 0.53751248, 0.7789433 ],
        [0.35868529, 0.5938458 , 0.12776253]]])

In [18]:
np.random.randint(3,40,10).reshape(5,2)

array([[11, 34],
       [13, 23],
       [26,  6],
       [36, 32],
       [32, 20]])

In [19]:
np.identity(4) # square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# changing Data type usinf linspace array creation 
np.linspace(3,40,15)

array([ 3.        ,  5.64285714,  8.28571429, 10.92857143, 13.57142857,
       16.21428571, 18.85714286, 21.5       , 24.14285714, 26.78571429,
       29.42857143, 32.07142857, 34.71428571, 37.35714286, 40.        ])

In [21]:
a = np.linspace(3,40,15)
a.astype(np.int32).reshape(3,5)

array([[ 3,  5,  8, 10, 13],
       [16, 18, 21, 24, 26],
       [29, 32, 34, 37, 40]])

In [22]:
# Array operations
# MAthematical operator , + , - , * , / %
# must be same size and same dimention

a = np.arange(2,12).reshape(5,2)
b = np.arange(10,20).reshape(5,2)
c = a + b
c


array([[12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [23]:
np.arange(2,12).reshape(5,2)

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
np.arange(10,20).reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [25]:
a + b

array([[12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30]])

In [26]:
# different shape
a = np.arange(2,12).reshape(5,2)
b = np.arange(10,20).reshape(2,5)
c = a + b
c


ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [27]:
# linsapce( start/lower rangs, end/upper range, total number/items )
np.linspace(3,12,3)

array([ 3. ,  7.5, 12. ])

In [28]:
np.linspace(3,12,10).reshape(5,2).astype(np.int32)

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
# changing Data type
a4 = np.linspace(5,20,4)
a4.astype(np.int32)

array([ 5, 10, 15, 20])

In [30]:
# Array operations. Mathematical operation
a5 = np.arange(12,24).reshape(3,4)
a6 = np.arange(1,13).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
a6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
# add
a5 + a6

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

In [33]:
# subtract
a5 - a6

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [34]:
# multiply
a5 * a6

array([[ 12,  26,  42,  60],
       [ 80, 102, 126, 152],
       [180, 210, 242, 276]])

In [35]:
# Division
a5 / a6

array([[12.        ,  6.5       ,  4.66666667,  3.75      ],
       [ 3.2       ,  2.83333333,  2.57142857,  2.375     ],
       [ 2.22222222,  2.1       ,  2.        ,  1.91666667]])

In [36]:
# Reminder
a5 % a6

array([[ 0,  1,  2,  3],
       [ 1,  5,  4,  3],
       [ 2,  1,  0, 11]])

In [37]:
# power
a5 ** a6

array([[         12,         169,        2744,       50625],
       [    1048576,    24137569,   612220032,  -196306143],
       [  898891776, -1771999463,   885692416,   480779105]])

In [38]:
# Array Attributes
a7 = np.arange(10) # 1D
a8 = np.arange(12).reshape(4,3) # 2D
a9 = np.arange(8).reshape(2,2,2) # 3D

In [39]:
# checking dimention of the array
a7.ndim

1

In [40]:
a8.ndim

2

In [41]:
a9.ndim

3

In [42]:
# shape: every dimention how much row and column 

a7.shape

(10,)

In [43]:
a8.shape

(4, 3)

In [44]:
# size: total number of items check
a7.size

10

In [45]:
a8.size

12

In [46]:
a9.size

8

In [47]:
# itemsize: memory space for every items. by defult int32- 4 bytes
a7.itemsize

4

In [48]:
a8.itemsize

4

In [49]:
# dtype: checking data type
a7.dtype

dtype('int32')

In [50]:
a8.dtype

dtype('int32')

In [51]:
a9.dtype

dtype('int32')

In [52]:
# Relational Operator
# output show : true or false
a7 < 50

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [53]:
a7 == 50

array([False, False, False, False, False, False, False, False, False,
       False])

In [54]:
a8 != 12

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
a8 >= 12

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [56]:
 # Array function
a10 = np.random.random((3,4))
a10

array([[0.95157913, 0.64314961, 0.93818508, 0.22282212],
       [0.00377729, 0.50947119, 0.52400873, 0.63831856],
       [0.85573164, 0.5849058 , 0.76052097, 0.84668795]])

In [57]:
a10 = np.round(a10)
a10

array([[1., 1., 1., 0.],
       [0., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
# max/min/sum/prod/exp/pow
# evry row highest value
# 1 -- row, 0 -- col
np.max(a8, axis=1)

array([ 2,  5,  8, 11])

In [59]:
a7 = np.arange(10) # 1D
a8 = np.arange(12).reshape(4,3) # 2D
a9 = np.arange(8).reshape(2,2,2) # 3D

In [60]:
np.min(a8, axis = 0)

array([0, 1, 2])

In [61]:
np.exp(a8)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [62]:
np.prod(a8)

0

In [63]:
np.sum(a8)

66

In [64]:
# mean/Median/std/var
np.mean(a8)

5.5

In [65]:
np.std(a8)

3.452052529534663

In [66]:
np.median(a8)

5.5

In [67]:
np.var(a8)

11.916666666666666

In [68]:
# Trigonometirc function: sin, cos, tan
np.sin(A8)

NameError: name 'A8' is not defined

In [69]:
np.cos(A8)

NameError: name 'A8' is not defined

In [70]:
np.cos(a8)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ]])

In [71]:
# Dot products: must be first matrix cols number and 2nd matrix row number same
a11 = np.arange(18).reshape(6,3)
a12 = np.arange(24).reshape(3,8)

In [72]:
a11

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [73]:
a12

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [74]:
np.dot(a11,a12)

array([[ 40,  43,  46,  49,  52,  55,  58,  61],
       [112, 124, 136, 148, 160, 172, 184, 196],
       [184, 205, 226, 247, 268, 289, 310, 331],
       [256, 286, 316, 346, 376, 406, 436, 466],
       [328, 367, 406, 445, 484, 523, 562, 601],
       [400, 448, 496, 544, 592, 640, 688, 736]])

In [75]:
# log and exponents
np.log(a11)

C:\Users\User\AppData\Local\Temp\ipykernel_260\339787899.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a11)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334]])

In [76]:
np.exp(a11)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07]])

In [77]:
# round/fllor/ceil
# round -- round near integer value
# floor - near left side deciaml point
# ceil - near right side deciaml point

a13 = np.linspace(1,5,10).reshape(2,5)
a13

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [78]:
np.round(a13)

array([[1., 1., 2., 2., 3.],
       [3., 4., 4., 5., 5.]])

In [79]:
np.floor(a13)

array([[1., 1., 1., 2., 2.],
       [3., 3., 4., 4., 5.]])

In [80]:
np.ceil(a13)

array([[1., 2., 2., 3., 3.],
       [4., 4., 5., 5., 5.]])

In [81]:
# indexing and slicing
# indexing
a7 = np.arange(10) # 1D
a8 = np.arange(24).reshape(4,3,2) # 2D
a9 = np.arange(8).reshape(2,4) # 3D

In [82]:
a8

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [83]:
a9

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [84]:
# 1d matrix indexing 
# positive start from 0 and negative start from -1
a7[2]

2

In [85]:
# 2D matrix indexing
# [row,col]
a9

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
# 6
a9[1,2]

6

In [87]:
# 4
a9[1,0]

4

In [88]:
# 3D indexing
# 1st select wich 2D? then row the col[2,1,0]--> 2 no 2D cell the 1 no row then 0 no col
a8

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [89]:
# 15
a8[2,1,1]

15

In [90]:
# 23
a8[3,2,1]

23

In [91]:
# 22,23
a8[3,2,:]

array([22, 23])

In [92]:
a8

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [93]:
#2D slicing
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
# 5 6 , 9 10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [95]:
# 0 3 , 8 11
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [96]:
# 1 3 , 9 11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [97]:
# 3D slicing
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [98]:
# middle 2D array
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [99]:
# middle 2D array 1 rno row 1 no col
a3[1,1,1]

13

In [100]:
# middle 2D array 1 rno row all col
a3[1,1,:]

array([12, 13, 14])

In [101]:
# 1st and last 2D
a[::2]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [102]:
# 2nd 2D and row
a3[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [103]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
# 2nd 2D and last col
a3[1,:,-1]

array([11, 14, 17])

In [105]:
# Iterating
# 1D 
a1 = np.arange(10)
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [106]:
# 2D iterating
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [107]:
# 3D iterating
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [108]:
# every value of 3D array print. it is very useful method for pandas and data analysis
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [109]:
# reshaping functions
# reshape --a laready used
# transpose - row convert col and col convert row
# ravle --- all value convert into 1D array

a = np.random.random(24).reshape(4,6)
b = np.round(a)

In [110]:
np.transpose(b)

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [111]:
np.ravel(b) # convert it into 1D array

array([0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 0., 0.])

In [112]:
# stucking -- two or more array add vertically and horizontally. must shape must be same
c = np.arange(16).reshape(4,4)
d = np.linspace(20,36,16).reshape(4,4)

In [113]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
e = d.astype(np.int32)

In [115]:
e

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 36]])

In [116]:
np.hstack((c,e)) # horizontal stack

array([[ 0,  1,  2,  3, 20, 21, 22, 23],
       [ 4,  5,  6,  7, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 28, 29, 30, 31],
       [12, 13, 14, 15, 32, 33, 34, 36]])

In [117]:
np.vstack((c,e)) # vertical stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 36]])

In [118]:
# spliting ---> equally divided . Used: Students dataset branch wise split kora
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [119]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]